[phases.setup]
nixPkgs = ['npx']
aptPkgs = ['build-essential']

[phases.install]
cmds = ['npx bun install --ignore-scripts']

[phases.build]
cmds = ['npx bun run build']

[start]
cmd = 'npx bun run start'
